import type { Express } from "express";
import { env } from "../config/env";
import adminRoutes from "../modules/admin/admin.routes";
import academyRoutes from "../modules/academy/academy.routes";
import certificateRoutes from "../modules/academy/certificates/certificate.routes";
import examRoutes from "../modules/academy/exams/exam.routes";
import quizRoutes from "../modules/academy/quizzes/quiz.routes";
import announcementRoutes from "../modules/announcements/announcement.routes";
import applicationsRoutes, { leaderApplicationsRouter, partnerApplicationsRouter } from "../modules/applications/application.routes";
import assignmentRoutes from "../modules/assignments/assignment.routes";
import attendanceRoutes from "../modules/attendance/attendance.routes";
import authRoutes from "../modules/auth/auth.routes";
import certificationLevelRoutes from "../modules/certification-levels/certificationLevel.routes";
import clusterRoutes from "../modules/clusters/cluster.routes";
import clusterCenterRoutes from "../modules/cluster-centers/clusterCenter.routes";
import deploymentRoutes from "../modules/deployments/deployment.routes";
import leaderForumRoutes from "../modules/leader-forums/leaderForum.routes";
import meetingRoutes from "../modules/meetings/meeting.routes";
import notificationRoutes from "../modules/notifications/notification.routes";
import reportRoutes from "../modules/reports/report.routes";
import resourceRoutes from "../modules/resources/resource.routes";
import roleRoutes from "../modules/roles/role.routes";
import skillsRoutes from "../modules/skills/skills.routes";
import socialLinkRoutes from "../modules/social-links/socialLink.routes";
import uploadRoutes from "../modules/uploads/upload.routes";
import communicationRoutes, { prayerRouter, projectUpdateRouter } from "../modules/communication/communication.routes";
import userRoutes from "../modules/users/user.routes";

export function registerRoutes(app: Express): void {
  const base = env.API_PREFIX;
  app.use(`${base}/auth`, authRoutes);
  app.use(`${base}/users`, userRoutes);
  app.use(`${base}/roles`, roleRoutes);
  app.use(`${base}/clusters`, clusterRoutes);
  app.use(`${base}/cluster-centers`, clusterCenterRoutes);
  app.use(`${base}/resources`, resourceRoutes);
  app.use(`${base}/attendance`, attendanceRoutes);
  app.use(`${base}/academy`, academyRoutes);
  app.use(`${base}/quizzes`, quizRoutes);
  app.use(`${base}/exams`, examRoutes);
  app.use(`${base}/certificates`, certificateRoutes);
  app.use(`${base}/meetings`, meetingRoutes);
  app.use(`${base}/deployments`, deploymentRoutes);
  app.use(`${base}/skills`, skillsRoutes);
  app.use(`${base}/certification-levels`, certificationLevelRoutes);
  app.use(`${base}/reports`, reportRoutes);
  app.use(`${base}/announcements`, announcementRoutes);
  app.use(`${base}/partner-applications`, partnerApplicationsRouter);
  app.use(`${base}/leader-applications`, leaderApplicationsRouter);
  app.use(`${base}/applications`, applicationsRoutes);
  app.use(`${base}/assignments`, assignmentRoutes);
  app.use(`${base}/communication`, communicationRoutes);
  app.use(`${base}/prayer-networks`, prayerRouter);
  app.use(`${base}/project-updates`, projectUpdateRouter);
  app.use(`${base}/leader-forums`, leaderForumRoutes);
  app.use(`${base}/social-links`, socialLinkRoutes);
  app.use(`${base}/notifications`, notificationRoutes);
  app.use(`${base}/admin`, adminRoutes);
  app.use(`${base}/uploads`, uploadRoutes);
}
